# Generated by Django 2.0 on 2019-12-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventario', '0002_delete_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ambiente', models.CharField(max_length=4)),
                ('mon_ambiente', models.CharField(max_length=60)),
                ('cod_ambiente', models.CharField(max_length=9)),
                ('obs_ambiente', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='cabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_color', models.CharField(max_length=3)),
                ('nom_color', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_departamento', models.CharField(max_length=2)),
                ('mon_departamento', models.CharField(max_length=60)),
                ('obs_departamento', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='direccionGerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dirger', models.CharField(max_length=2)),
                ('nom_dirger', models.CharField(max_length=60)),
                ('obs_dirger', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_distrito', models.CharField(max_length=4)),
                ('mon_distrito', models.CharField(max_length=60)),
                ('obs_distrito', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_edificio', models.CharField(max_length=1)),
                ('nom_edificio', models.CharField(max_length=60)),
                ('deta_edificio', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_es', models.CharField(max_length=1)),
                ('nom_es', models.CharField(max_length=1)),
                ('deta_es', models.CharField(blank=True, max_length=60)),
                ('obs_es', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='etiquetado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_eti', models.CharField(max_length=1)),
                ('nom_eti', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ficha', models.CharField(max_length=3)),
                ('num_ficha', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='jefeUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_jefusuario', models.CharField(max_length=8)),
                ('numero_doc_jefusuario', models.CharField(max_length=8)),
                ('nom_jefusuario', models.CharField(max_length=60)),
                ('ap_pat_usuario', models.CharField(max_length=60)),
                ('ap_mat_usuario', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('obs_jefusuario', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_marca', models.CharField(max_length=3)),
                ('marca', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_modalidad', models.CharField(max_length=2)),
                ('modalidad_contratacion', models.CharField(max_length=8)),
                ('obs_modalidad', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_oficina', models.CharField(max_length=2)),
                ('nom_oficina', models.CharField(max_length=60)),
                ('obs_oficina', models.CharField(blank=True, max_length=60)),
                ('gere_oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.direccionGerencia')),
            ],
        ),
        migrations.CreateModel(
            name='operatividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ope', models.CharField(max_length=1)),
                ('nom_ope', models.CharField(max_length=1)),
                ('deta_ope', models.CharField(max_length=2)),
                ('obs_ope', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_piso', models.CharField(max_length=2)),
                ('nom_psio', models.CharField(max_length=60)),
                ('deta_piso', models.CharField(blank=True, max_length=60, null=True)),
                ('obs_piso', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_provincia', models.CharField(max_length=3)),
                ('mon_provincia', models.CharField(max_length=60)),
                ('obs_provincia', models.CharField(blank=True, max_length=60)),
                ('depa_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_re', models.CharField(max_length=2)),
                ('nom_re', models.CharField(max_length=60)),
                ('deta_re', models.CharField(blank=True, max_length=60)),
                ('obs_re', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sector', models.CharField(max_length=2)),
                ('nom_sector', models.CharField(max_length=60)),
                ('obs_sector', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_sede', models.CharField(max_length=3)),
                ('nom_sede', models.CharField(max_length=60)),
                ('direc_fis_sede', models.CharField(blank=True, max_length=60, null=True)),
                ('obs_sede', models.CharField(blank=True, max_length=60, null=True)),
                ('depa_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.departamento')),
                ('dis_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.distrito')),
                ('provi_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='situacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_situ', models.CharField(max_length=2)),
                ('nom_situ', models.CharField(max_length=60)),
                ('obs_situ', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='suboficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_suboficina', models.CharField(max_length=2)),
                ('nom_suboficina', models.CharField(max_length=60)),
                ('obs_suboficina', models.CharField(blank=True, max_length=60)),
                ('gere_suboficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.direccionGerencia')),
                ('ofi_suboficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='tipoDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_documento', models.CharField(max_length=1)),
                ('tipo_doc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_usuario', models.CharField(max_length=8)),
                ('numero_doc_usuario', models.CharField(max_length=8)),
                ('nom_final_usuario', models.CharField(max_length=60)),
                ('ap_pat_usuario', models.CharField(max_length=60)),
                ('ap_mat_usuario', models.CharField(max_length=60)),
                ('nom_usuario', models.CharField(max_length=60)),
                ('obs_usuario', models.CharField(blank=True, max_length=60)),
                ('moda_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.modalidad')),
                ('t_doc_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.tipoDoc')),
            ],
        ),
        migrations.AddField(
            model_name='jefeusuario',
            name='moda_jefusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.modalidad'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='sede_edificio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.sede'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='prov_distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.provincia'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='depa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.departamento'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='dire_gere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.direccionGerencia'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='distri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.distrito'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='moda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.modalidad'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='ofi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.oficina'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='pis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.piso'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='provi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.provincia'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='sed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.sede'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='subofi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.suboficina'),
        ),
        migrations.AddField(
            model_name='cabecera',
            name='usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.usuario'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='piso_ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.piso'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='sector_ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.sector'),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='sede_ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.sede'),
        ),
    ]
