# Generated by Django 2.0 on 2019-12-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_auto_20191206_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='cod_departamento',
            field=models.CharField(max_length=3),
        ),
    ]
