# Generated by Django 2.0 on 2019-12-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_auto_20191206_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='mon_departamento',
            new_name='nom_departamento',
        ),
    ]
