# Generated by Django 2.0 on 2019-12-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_auto_20191206_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distrito',
            old_name='mon_distrito',
            new_name='nom_distrito',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='mon_provincia',
            new_name='nom_provincia',
        ),
    ]
