# Generated by Django 2.0 on 2019-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_auto_20191206_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidad',
            name='modalidad_contratacion',
            field=models.CharField(max_length=60),
        ),
    ]
