# Generated by Django 2.0 on 2019-12-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_auto_20191206_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ambi',
        ),
    ]
