# Generated by Django 2.0 on 2019-12-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0011_remove_usuario_ambi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='usuario_ambiente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Inventario.usuario'),
            preserve_default=False,
        ),
    ]
