# Generated by Django 2.0 on 2019-12-06 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0013_base0'),
    ]

    operations = [
        migrations.AddField(
            model_name='base0',
            name='usuario_bae0',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Inventario.usuario'),
            preserve_default=False,
        ),
    ]
