# Generated by Django 2.0 on 2019-12-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0014_base0_usuario_bae0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base0',
            old_name='usuario_bae0',
            new_name='usuario_base0',
        ),
    ]
