# Generated by Django 2.0 on 2019-12-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0016_base12019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='base12019',
            unique_together={('id', 'base0_fk')},
        ),
    ]
