# Generated by Django 2.0 on 2019-12-07 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventario', '0017_auto_20191206_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='base12019',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='base12019',
            unique_together={('base0_fk', 'user')},
        ),
    ]
