# Generated by Django 2.0 on 2019-12-08 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0018_auto_20191207_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edifi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.edificio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='jef',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.jefeUsuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='sect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.sector'),
            preserve_default=False,
        ),
    ]
