# Generated by Django 2.0 on 2019-12-08 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0019_auto_20191207_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base0',
            name='piso_base0',
        ),
        migrations.RemoveField(
            model_name='base0',
            name='sede_base0',
        ),
        migrations.AddField(
            model_name='base0',
            name='a_fabri',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='base0',
            name='chasis',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='base0',
            name='col',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base0',
            name='descripcion',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='base0',
            name='detalle',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='base0',
            name='est',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base0',
            name='mar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base0',
            name='medida',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='base0',
            name='modelo',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='base0',
            name='motor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='base0',
            name='observacion1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='base0',
            name='observacion2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='base0',
            name='observacion3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='base0',
            name='op',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.operatividad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base0',
            name='placa',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='base0',
            name='puertas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='base0',
            name='serie',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='base0',
            name='tar_propiedad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='base0',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='base0',
            name='codigo_sbn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
