# Generated by Django 2.0 on 2019-12-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0020_auto_20191207_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base0',
            name='codigo_interno',
            field=models.CharField(blank=True, default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='base0',
            name='codigo_sbn',
            field=models.CharField(blank=True, default='', max_length=12),
            preserve_default=False,
        ),
    ]
