# Generated by Django 2.0 on 2019-12-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0022_ambiente_cod_correlativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='cod_correlativo',
            field=models.CharField(max_length=4),
        ),
    ]
