# Generated by Django 2.0 on 2019-12-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0024_auto_20191208_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='depa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dire_gere',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='distri',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='edifi',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='jef',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ofi',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='pis',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='provi',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sect',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sed',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='subofi',
        ),
    ]
