# Generated by Django 2.0 on 2019-12-09 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0025_auto_20191208_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='usuario_ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
        migrations.AlterField(
            model_name='base0',
            name='usuario_base0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
