# Generated by Django 2.0 on 2019-12-09 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0026_auto_20191208_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='usuario_ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
        migrations.AlterField(
            model_name='base0',
            name='usuario_base0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ap_mat_usuario',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ap_pat_usuario',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nom_final_usuario',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nom_usuario',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
