# Generated by Django 2.0 on 2019-12-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0027_auto_20191209_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='cod_correlativo',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='sector_ambiente',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='usuario_ambiente',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='depart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='base0',
            name='usuario_base0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
