# Generated by Django 2.0 on 2019-12-09 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0028_auto_20191209_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='depart',
        ),
        migrations.AlterField(
            model_name='base0',
            name='usuario_base0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
