# Generated by Django 2.0 on 2019-12-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0029_auto_20191209_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base0',
            name='usuario_base0',
        ),
    ]
