# Generated by Django 2.0 on 2019-12-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0030_remove_base0_usuario_base0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base0',
            name='codigo_interno',
            field=models.IntegerField(blank=True, max_length=5),
        ),
    ]
