# Generated by Django 2.0 on 2019-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0031_auto_20191209_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base0',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
