# Generated by Django 2.0 on 2019-12-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0032_auto_20191209_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='cod_ficha',
        ),
        migrations.AddField(
            model_name='ficha',
            name='fecha_ficha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='num_ficha',
            field=models.IntegerField(max_length=20),
        ),
    ]
