# Generated by Django 2.0 on 2019-12-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0033_auto_20191210_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='num_ficha',
            field=models.IntegerField(),
        ),
    ]
