# Generated by Django 2.0 on 2019-12-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0034_auto_20191210_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fecha_ficha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
