# Generated by Django 2.0 on 2019-12-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0036_ficha_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='ambiente',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='ficha',
            name='dependencia',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='ficha',
            name='piso',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='ficha',
            name='sede',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
