# Generated by Django 2.0 on 2019-12-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0039_auto_20191210_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='ficha',
            unique_together={('idusuario',)},
        ),
    ]
