# Generated by Django 2.0 on 2019-12-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0040_auto_20191210_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='base12019',
            name='idficha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.ficha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='base12019',
            unique_together=set(),
        ),
    ]
