# Generated by Django 2.0 on 2019-12-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0047_auto_20191211_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidad',
            name='cod_modalidad',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
