# Generated by Django 2.0 on 2019-12-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0049_auto_20191211_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficina',
            name='cod_oficina',
        ),
        migrations.RemoveField(
            model_name='oficina',
            name='gere_oficina',
        ),
        migrations.RemoveField(
            model_name='suboficina',
            name='cod_suboficina',
        ),
        migrations.RemoveField(
            model_name='suboficina',
            name='gere_suboficina',
        ),
        migrations.RemoveField(
            model_name='suboficina',
            name='ofi_suboficina',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
