# Generated by Django 2.0 on 2019-12-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0050_auto_20191211_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direcciongerencia',
            name='cod_dirger',
        ),
        migrations.AddField(
            model_name='direcciongerencia',
            name='ofi_dirger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.oficina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direcciongerencia',
            name='subofi_dirger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.suboficina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
