# Generated by Django 2.0 on 2019-12-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0053_auto_20191211_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='cod_sede',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='dis_sede',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='provi_sede',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
