# Generated by Django 2.0 on 2019-12-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0056_auto_20191211_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piso',
            old_name='nom_psio',
            new_name='nom_piso',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
