# Generated by Django 2.0 on 2019-12-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0058_auto_20191211_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='cod_es',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
