# Generated by Django 2.0 on 2019-12-11 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0061_auto_20191211_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='cod_color',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
