# Generated by Django 2.0 on 2019-12-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0062_auto_20191211_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='base0',
            name='eti',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Inventario.etiquetado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base0',
            name='tipo',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
