# Generated by Django 2.0 on 2019-12-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0067_auto_20191211_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base0',
            name='codigo_sbn',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
