# Generated by Django 2.0 on 2019-12-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0074_auto_20191212_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='codgroup',
            field=models.CharField(default='G01', max_length=3),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
