# Generated by Django 2.0 on 2019-12-12 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0075_auto_20191212_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='codgroup',
            field=models.CharField(max_length=3),
        ),
    ]
