# Generated by Django 2.0 on 2019-12-12 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0076_auto_20191212_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='numero_aux',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
