# Generated by Django 2.0 on 2019-12-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0079_auto_20191212_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='cod_ambiente',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
