# Generated by Django 2.0 on 2019-12-15 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0087_auto_20191215_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base0',
            name='col',
            field=models.ForeignKey(default='S/C', on_delete=django.db.models.deletion.CASCADE, to='Inventario.color'),
        ),
        migrations.AlterField(
            model_name='base0',
            name='mar',
            field=models.ForeignKey(default='S/M', on_delete=django.db.models.deletion.CASCADE, to='Inventario.marca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
