# Generated by Django 2.0 on 2019-12-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0090_auto_20191215_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='base12019',
            name='codigo_sbn',
            field=models.CharField(default='999999999999', max_length=20),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
