# Generated by Django 2.0 on 2019-12-15 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0092_auto_20191215_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='base12019',
            unique_together={('base0_fk', 'codigo_sbn', 'codigo_conformidad')},
        ),
    ]
