# Generated by Django 2.0 on 2019-12-16 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0093_auto_20191215_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='base12019',
            name='item',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='idusuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.Usuario'),
        ),
    ]
